/*******************************************************************************
 *                                                                             *
 * Project:      OMEGA L4 Scanner                                              *
 * University:   Faculty of Information Technology, BUT                        *
 * Subject:      IPK: Computer Communications and Networks                     *
 *                                                                             *
 * File:         CommandLineOptions.hpp                                        *
 * Author:       Jan Kalina <xkalinj00>                                        *
 *                                                                             *
 * Created:      14.03.2025                                                    *
 * Last edit:    15.03.2025                                                    *
 *                                                                             *
 * Description:  Declaration of the CommandLineOptions class, which is         *
 *               responsible for handling command line options for the         *
 *               OMEGA L4 Scanner application.                                 *
 ******************************************************************************/
/**
 * @file CommandLineOptions.hpp
 * @author Jan Kalina \<xkalinj00>
 * @brief Header file for CommandLineOptions class.
 */

#ifndef COMMAND_LINE_OPTIONS_HPP
#define COMMAND_LINE_OPTIONS_HPP

#include "Common/OmegaDataTypes.hpp" // PortRange
#include <string> // std::string
#include <chrono> // std::chrono::milliseconds

namespace OmegaL4Scanner::Common
{
    /**
     * @class CommandLineOptions
     * @brief Handles command line options for the OMEGA L4 Scanner application.
     */
    class CommandLineOptions final {
    public:
        /**
         * @brief Default constructor for CommandLineOptions class.
         */
        CommandLineOptions();

        std::string mInterfaceName;             /**< Name of the network interface.                 */
        std::vector<PortRange> mTcpPorts;       /**< List of TCP ports to scan.                     */
        std::vector<PortRange> mUdpPorts;       /**< List of UDP ports to scan.                     */
        std::string mTarget;                    /**< Target hostname or IP address to scan.         */
        std::chrono::milliseconds mWaitTimeout; /**< Timeout in milliseconds to wait for responses. */

        /**
         * @brief Equality operator for CommandLineOptions class.
         *
         * @details This operator compares two CommandLineOptions objects for
         *          equality. It is automatically generated by the compiler
         *          and compares all member variables.
         *
         * @return True if all member variables are equal, False otherwise.
         */
        bool operator==(const CommandLineOptions &) const = default;
    }; // CommandLineOptions
} // OmegaL4Scanner::Common

#endif // COMMAND_LINE_OPTIONS_HPP

/*** end of file CommandLineOptions.hpp ***/
